### ISSUE TITLE
Ensure users are being removed from global cache

### ISSUE THREAD

**Issue by Auralytical** [discord-net/Discord.Net#113]
This was never actually tested as far as I know - users should be removed from global cache when they are no longer in any visible guild, nor have a current dm channel.

**Comment by RogueException** [comment]
With the removal of shared datastore support, I wonder if this system can be made much more solid using WeakReferences...

**Comment by RogueException** [comment]
I recently patched one of these memory leaks as part the DownloadUsersAsync fix. We should check if this is still a problem.

**Comment by khionu** [comment]
This can be tested as part of https://github.com/RogueException/Discord.Net/issues/272
