### ISSUE TITLE
Cache Integrity

### ISSUE THREAD

**Issue by khionu** [discord-net/Discord.Net#272]
Opening this issue to track known issues with Cache Integrity. I've noticed several, plus we have at least two separate issues that are related.
- GuildPermissions
  - When a Role gains a new permission
- Users"
  - Avatar Change, retains old hash
  - Username Change, retains old username

To Verify
- Discriminators

Pre-RC Update: Someone should do a series of tests to ensure the integrity of all entities and their properties.

**Comment by FiniteReality** [comment]
Do usernames fall under this issue too? 

![](https://cloud.githubusercontent.com/assets/21000186/19127255/270ea99a-8b36-11e6-87ad-181192661536.png)

Between the eval commands, I changed my username to FiniteTesting and the username failed to update. Earlier I tried running UpdateAsync but that threw a NotSupportedException.

**Comment by khionu** [comment]
Yes, it does

**Comment by RogueException** [comment]
Cache logic was redone in beta2, let me know if there are any issues

**Comment by khionu** [comment]
\o/

**Comment by khionu** [comment]
Added amendment to OP

**Comment by khionu** [comment]
I think this is worked on enough to be closed, but I'll leave that to the current maintainers
